name: Server Starting

on:
  repository_dispatch:
    types: start_action

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Installing requirements.txt
      run: |
        python3 -m pip install -r ./SourceCode/requirements.txt
    - name: Decrypting the SC
      run: |
        python3 decrypt.py ${{ secrets.KEY }}
    - name: Running The script.sh
      run: |
        sudo ./SourceCode/script.sh
